// Avia Solutions - BA London Heathrow to San Jose route business case deck
// Generated by the QSI deck generator. House style: UK English, no em/en dashes, "circa".
const pptxgen = require("pptxgenjs");

const pres = new pptxgen();
pres.layout = "LAYOUT_WIDE"; // 13.333 x 7.5
pres.author = "Avia Solutions";
pres.company = "Avia Solutions";
pres.title = "London Heathrow to San Jose - Route Business Case";
pres.subject = "British Airways LHR-SJC route forecast and business case";

// ---- Palette ----
const NAVY = "13243B";       // deep navy (dominant)
const NAVY2 = "1E3A5F";      // mid navy
const GOLD = "C8A45C";       // accent (sparing)
const SLATE = "2B2B2B";      // body text
const MUTED = "6B7A8D";      // captions
const LIGHT = "F4F6F8";      // light panel
const PANEL = "EAEEF2";      // slightly darker panel
const WHITE = "FFFFFF";
const BLUE = "3E6CA6";       // chart blue
const TEAL = "2E8E94";       // secondary chart

const HEAD = "Cambria";      // serif headers (QA-safe, premium)
const BODY = "Calibri";      // sans body (QA-safe)

const W = 13.333, H = 7.5;
const MX = 0.7; // left margin

let pageNo = 0;

function footer(slide, section) {
  pageNo++;
  slide.addText(
    [{ text: "Avia Solutions", options: { color: MUTED, bold: true } },
     { text: "   British Airways  |  London Heathrow - San Jose", options: { color: MUTED } }],
    { x: MX, y: H - 0.42, w: 9.5, h: 0.3, fontSize: 8.5, fontFace: BODY, margin: 0, valign: "middle" });
  slide.addText(String(pageNo), { x: W - 1.0, y: H - 0.42, w: 0.5, h: 0.3, fontSize: 9, fontFace: BODY,
    color: MUTED, align: "right", valign: "middle", margin: 0 });
  if (section) {
    slide.addText(section.toUpperCase(), { x: W - 4.6, y: H - 0.42, w: 3.3, h: 0.3, fontSize: 8,
      fontFace: BODY, color: MUTED, align: "right", valign: "middle", charSpacing: 1, margin: 0 });
  }
}

function title(slide, text, sub) {
  slide.addText(text, { x: MX, y: 0.45, w: W - 2*MX, h: 0.7, fontSize: 27, fontFace: HEAD,
    color: NAVY, bold: true, margin: 0, valign: "middle" });
  if (sub) {
    slide.addText(sub, { x: MX, y: 1.18, w: W - 2*MX, h: 0.4, fontSize: 13, fontFace: BODY,
      color: GOLD, italic: true, margin: 0, valign: "middle" });
  }
}

function sourceLine(slide, text, y) {
  slide.addText("Sources: " + text, { x: MX, y: y || (H - 0.78), w: W - 2*MX, h: 0.33,
    fontSize: 8, fontFace: BODY, color: MUTED, italic: true, margin: 0, valign: "middle" });
}

function shadow() { return { type: "outer", color: "000000", blur: 7, offset: 2, angle: 90, opacity: 0.12 }; }

// Stat callout card
function statCard(slide, x, y, w, h, value, label, sub, accent) {
  slide.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, fill: { color: WHITE },
    line: { color: PANEL, width: 1 }, rectRadius: 0.06, shadow: shadow() });
  slide.addText(value, { x: x+0.18, y: y+0.16, w: w-0.36, h: h*0.45, fontSize: 30, fontFace: HEAD,
    color: accent || NAVY, bold: true, margin: 0, valign: "middle", align: "left", autoFit: true });
  slide.addText(label, { x: x+0.2, y: y+h*0.52, w: w-0.4, h: h*0.24, fontSize: 11.5, fontFace: BODY,
    color: SLATE, bold: true, margin: 0, valign: "top" });
  if (sub) slide.addText(sub, { x: x+0.2, y: y+h*0.72, w: w-0.4, h: h*0.26, fontSize: 9.5, fontFace: BODY,
    color: MUTED, margin: 0, valign: "top" });
}

// Photo upload placeholder
function photoSlot(slide, x, y, w, h, label) {
  slide.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, fill: { color: PANEL },
    line: { color: MUTED, width: 1, dashType: "dash" }, rectRadius: 0.05 });
  slide.addText([
    { text: "IMAGE SLOT", options: { bold: true, color: NAVY2, fontSize: 11, breakLine: true, charSpacing: 1 } },
    { text: label, options: { color: MUTED, fontSize: 10, breakLine: true } },
    { text: "Airport to supply", options: { color: MUTED, fontSize: 8.5, italic: true } },
  ], { x: x+0.1, y: y, w: w-0.2, h: h, align: "center", valign: "middle", fontFace: BODY, margin: 0 });
}

// Bullet block
function bullets(slide, x, y, w, h, items, fontSize) {
  slide.addText(items.map((t, i) => ({ text: t,
    options: { bullet: { code: "2022", indent: 14 }, color: SLATE, breakLine: true, paraSpaceAfter: 8 } })),
    { x, y, w, h, fontSize: fontSize || 13, fontFace: BODY, valign: "top", margin: 0 });
}

function sectionDivider(num, name, photoLabel) {
  const s = pres.addSlide();
  s.background = { color: NAVY };
  s.addText(num, { x: MX, y: 2.0, w: 3, h: 1.4, fontSize: 72, fontFace: HEAD, color: GOLD, bold: true, margin: 0 });
  s.addText(name, { x: MX, y: 3.45, w: 7.4, h: 1.6, fontSize: 34, fontFace: HEAD, color: WHITE, bold: true, margin: 0, valign: "top" });
  // photo panel on right
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: 8.5, y: 1.4, w: 4.1, h: 4.7, fill: { color: NAVY2 },
    line: { color: GOLD, width: 1, dashType: "dash" }, rectRadius: 0.05 });
  s.addText([
    { text: "IMAGE SLOT", options: { bold: true, color: GOLD, fontSize: 12, breakLine: true, charSpacing: 1 } },
    { text: photoLabel, options: { color: "C9D4E0", fontSize: 11, breakLine: true } },
    { text: "Airport to supply", options: { color: MUTED, fontSize: 9, italic: true } },
  ], { x: 8.6, y: 1.4, w: 3.9, h: 4.7, align: "center", valign: "middle", fontFace: BODY, margin: 0 });
  pageNo++;
  s.addText(String(pageNo), { x: W - 1.0, y: H - 0.42, w: 0.5, h: 0.3, fontSize: 9, fontFace: BODY, color: "8FA0B3", align: "right", margin: 0 });
  return s;
}

// ============================================================ SLIDE 1: COVER
{
  const s = pres.addSlide();
  s.background = { color: NAVY };
  // photo band slot across top
  s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: W, h: 2.7, fill: { color: NAVY2 } });
  s.addText([
    { text: "IMAGE SLOT   ", options: { bold: true, color: GOLD, fontSize: 11, charSpacing: 1 } },
    { text: "San Jose / Silicon Valley hero image (airport to supply)", options: { color: "AEBCCB", fontSize: 11, italic: true } },
  ], { x: MX, y: 0.2, w: 11, h: 0.4, align: "left", valign: "middle", fontFace: BODY, margin: 0 });

  s.addText("A unique opportunity to serve\nSilicon Valley from London", { x: MX, y: 3.0, w: 11.5, h: 1.6,
    fontSize: 40, fontFace: HEAD, color: WHITE, bold: true, margin: 0, lineSpacingMultiple: 1.0 });
  s.addText("Norman Y. Mineta San Jose International Airport   |   London Heathrow to San Jose   |   Daily Boeing 787",
    { x: MX, y: 4.85, w: 11.8, h: 0.5, fontSize: 16, fontFace: BODY, color: GOLD, margin: 0 });

  s.addText([
    { text: "Route forecast and business case", options: { color: "C9D4E0", fontSize: 13, breakLine: true } },
    { text: "Prepared by Avia Solutions  |  June 2026", options: { color: MUTED, fontSize: 12 } },
  ], { x: MX, y: 5.7, w: 8, h: 0.8, fontFace: BODY, margin: 0, valign: "top" });

  // logo slots
  s.addText("[ Airport logo ]      [ Avia Solutions logo ]      [ British Airways logo ]",
    { x: MX, y: 6.7, w: 11, h: 0.4, fontSize: 10, fontFace: BODY, color: MUTED, italic: true, margin: 0 });
}

// ============================================================ SLIDE 2: ENDORSEMENT
{
  const s = pres.addSlide();
  s.background = { color: NAVY };
  s.addText("“", { x: 0.5, y: 0.7, w: 2, h: 2, fontSize: 120, fontFace: HEAD, color: GOLD, bold: true, margin: 0 });
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: 2.2, y: 1.9, w: 9.0, h: 2.6, fill: { color: NAVY2 },
    line: { color: GOLD, width: 1, dashType: "dash" }, rectRadius: 0.05 });
  s.addText([
    { text: "QUOTE SLOT", options: { bold: true, color: GOLD, fontSize: 12, charSpacing: 1, breakLine: true } },
    { text: "Endorsement from the Mayor of San Jose or the Airport Director", options: { color: "C9D4E0", fontSize: 13, breakLine: true } },
    { text: "(airport to supply the quotation and attribution)", options: { color: MUTED, fontSize: 10, italic: true } },
  ], { x: 2.5, y: 1.9, w: 8.4, h: 2.6, align: "center", valign: "middle", fontFace: BODY, margin: 0 });
  s.addText("Welcome to San Jose, capital of Silicon Valley", { x: 2.2, y: 4.9, w: 9, h: 0.6,
    fontSize: 18, fontFace: HEAD, color: WHITE, italic: true, margin: 0 });
  pageNo++;
  s.addText(String(pageNo), { x: W - 1.0, y: H - 0.42, w: 0.5, h: 0.3, fontSize: 9, fontFace: BODY, color: "8FA0B3", align: "right", margin: 0 });
}

// ============================================================ SLIDE 3: CONTENTS
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Contents");
  const items = [
    ["01", "Why Silicon Valley", "The wealthiest, most innovative metro in the United States, and the global centre of the AI economy"],
    ["02", "Two genuine tech centres", "London and Silicon Valley: a two-way corporate, tech and life-sciences corridor"],
    ["03", "San Jose airport", "A widebody-capable airport at the heart of the Valley, with the support to back a returning service"],
    ["04", "The forecast", "Catchment, point-to-point and connecting demand, revenue, and the case for net-new traffic"],
    ["05", "Methodology and the case for now", "The Avia QSI approach, and what has changed since 2023"],
  ];
  let y = 1.8;
  items.forEach(([n, t, d]) => {
    s.addText(n, { x: MX, y, w: 0.9, h: 0.8, fontSize: 26, fontFace: HEAD, color: GOLD, bold: true, margin: 0, valign: "top" });
    s.addText(t, { x: MX+1.0, y, w: 10.6, h: 0.4, fontSize: 17, fontFace: HEAD, color: NAVY, bold: true, margin: 0, valign: "top" });
    s.addText(d, { x: MX+1.0, y: y+0.42, w: 11.0, h: 0.5, fontSize: 11.5, fontFace: BODY, color: MUTED, margin: 0, valign: "top" });
    y += 1.0;
  });
  footer(s, "Contents");
}

// ============================================================ SLIDE 4: OPPORTUNITY AT A GLANCE
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "The opportunity for British Airways", "A daily Boeing 787 linking London Heathrow with the heart of Silicon Valley");
  statCard(s, MX, 1.85, 3.7, 1.75, "249,800", "Point-to-point market", "Annual two-way O&D, London - San Jose", NAVY);
  statCard(s, MX+3.95, 1.85, 3.7, 1.75, "904,500", "Connecting market over London", "Beyond-hub demand the route can feed", BLUE);
  statCard(s, MX+7.9, 1.85, 3.7, 1.75, "circa 130,000", "Year 1 forecast passengers", "83.7% load factor on a daily 787", GOLD);

  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX, y: 3.95, w: 7.4, h: 2.5, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText("Proposed service", { x: MX+0.25, y: 4.1, w: 7, h: 0.4, fontSize: 14, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  s.addTable([
    [{ text: "Frequency", options: { bold: true } }, "Daily (7x weekly)"],
    [{ text: "Aircraft", options: { bold: true } }, "Boeing 787, circa 214 seats, four cabins"],
    [{ text: "Annual capacity", options: { bold: true } }, "155,792 two-way seats"],
    [{ text: "Premium share of demand", options: { bold: true } }, "circa 43%, supporting a high-yield service"],
  ], { x: MX+0.25, y: 4.55, w: 6.9, h: 1.8, fontSize: 11.5, fontFace: BODY, color: SLATE,
       border: { type: "solid", pt: 0.5, color: PANEL }, colW: [2.4, 4.5], valign: "middle", rowH: 0.4 });

  photoSlot(s, MX+7.7, 3.95, 3.9, 2.5, "World map of connecting flows, or San Jose skyline");
  sourceLine(s, "Avia QSI forecast model (validated reference case), to be refreshed on the live 2024-2025 base. Figures illustrative pending live run.");
  footer(s, "Summary");
}

// ============================================================ SECTION 01
sectionDivider("01", "Why Silicon Valley", "San Jose / Silicon Valley panorama");

// ---- SLIDE: wealthiest, most innovative metro
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "The wealthiest, most innovative metro in the US", "A premium catchment built for a high-yield London service");
  statCard(s, MX, 1.85, 2.85, 1.7, "$175,491", "Median household income", "Highest of the 50 largest US metros (2024)", NAVY);
  statCard(s, MX+3.05, 1.85, 2.85, 1.7, "$171,660", "GDP per capita", "Highest of any US metro", BLUE);
  statCard(s, MX+6.1, 1.85, 2.85, 1.7, "No. 1", "US city for patents", "200,778 granted, 2020-2024", TEAL);
  statCard(s, MX+9.15, 1.85, 2.45, 1.7, "44.9%", "of all US venture capital", "San Francisco metro, 2025", GOLD);

  bullets(s, MX, 3.95, 11.9, 1.9, [
    "San Jose - Sunnyvale - Santa Clara is the richest major metro in the country, roughly double the national median household income, and the densest pool of premium and business-class demand in the US.",
    "The San Jose - San Francisco cluster has ranked first in the world for innovation for six consecutive years (WIPO Global Innovation Index 2025), leading on both patents and venture deals per head.",
    "Silicon Valley holds the most concentrated set of global technology headquarters anywhere, led by Apple, Alphabet and NVIDIA.",
  ], 12.5);
  sourceLine(s, "US Census Bureau ACS 2024 (Sept 2025); BEA-derived metro GDP; CommercialCafe / USPTO (patents); PitchBook-NVCA Venture Monitor (Jan 2026); WIPO GII 2025.");
  footer(s, "Why Silicon Valley");
}

// ---- SLIDE: AI capital (what has changed)
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "The AI capital: what has changed since BA last looked", "The single biggest shift in the market since the route last flew");
  statCard(s, MX, 1.85, 3.55, 1.7, "$126bn", "Global AI funding to the Bay Area", "60% of the world total, 2025", NAVY);
  statCard(s, MX+3.75, 1.85, 3.55, 1.7, "81%", "of Bay Area startup capital", "went into AI in 2025", BLUE);
  statCard(s, MX+7.5, 1.85, 3.55, 1.7, "up to $100bn", "NVIDIA commitment to OpenAI", "announced 22 September 2025", GOLD);

  bullets(s, MX, 3.95, 7.4, 2.1, [
    "Silicon Valley is now the undisputed global centre of the AI industry. AI start-ups raised $211bn worldwide in 2025, and the Bay Area captured the majority of it.",
    "These are exactly the fast-scaling, capital-rich, internationally connected firms that generate premium long-haul demand, and many are building their largest non-US bases in London.",
    "When BA withdrew in 2023, this economy did not exist at today's scale. It is the strongest current reason a premium London service works.",
  ], 12);
  photoSlot(s, MX+7.7, 3.95, 3.9, 2.1, "NVIDIA campus, Santa Clara");
  sourceLine(s, "Crunchbase / HumanX AI Funding Report (Feb 2026); NVIDIA Newsroom (Sept 2025); PitchBook-NVCA.");
  footer(s, "Why Silicon Valley");
}

// ---- SLIDE: Tech HQs on SJC doorstep
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "The headquarters are on the airport's doorstep", "San Jose is inside the cluster, not adjacent to it");
  const rows = [
    [{ text: "Company", options: { bold: true, color: WHITE, fill: { color: NAVY } } },
     { text: "Location", options: { bold: true, color: WHITE, fill: { color: NAVY } } },
     { text: "From SJC", options: { bold: true, color: WHITE, fill: { color: NAVY }, align: "right" } }],
    ["NVIDIA", "Santa Clara", "circa 4 miles"],
    ["Apple (Apple Park)", "Cupertino", "circa 9 miles"],
    ["Google / Alphabet", "Mountain View", "circa 12 miles"],
    ["Adobe, eBay, PayPal, Cisco", "San Jose", "minutes"],
    ["Meta", "Menlo Park", "circa 18 miles"],
  ].map((r, i) => r.map((c, j) => typeof c === "string"
    ? { text: c, options: { fill: { color: i % 2 ? LIGHT : WHITE }, color: SLATE, align: j === 2 ? "right" : "left" } } : c));
  s.addTable(rows, { x: MX, y: 1.9, w: 6.3, colW: [2.7, 2.0, 1.6], fontSize: 12, fontFace: BODY,
    border: { type: "solid", pt: 0.5, color: PANEL }, valign: "middle", rowH: 0.42 });

  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX, y: 4.85, w: 6.3, h: 1.25, fill: { color: LIGHT }, line: { color: GOLD, width: 1 }, rectRadius: 0.05 });
  s.addText([
    { text: "SJC sits circa 10 miles from the centre of Silicon Valley. ", options: { bold: true } },
    { text: "SFO is circa 29 miles away, so SJC is roughly 19 miles closer to the densest tech cluster on earth.", options: {} },
  ], { x: MX+0.2, y: 4.95, w: 5.9, h: 1.05, fontSize: 12, fontFace: BODY, color: SLATE, valign: "middle", margin: 0 });

  photoSlot(s, MX+6.6, 1.9, 2.45, 2.0, "Google buildings, San Jose / Mountain View");
  photoSlot(s, MX+9.15, 1.9, 2.45, 2.0, "Apple Park, Cupertino");
  photoSlot(s, MX+6.6, 4.0, 5.0, 1.5, "NVIDIA HQ, Santa Clara (airport-supplied)");
  sourceLine(s, "Company sites; Santa Clara County; Rome2Rio / Visit San Jose proximity data (2026).");
  footer(s, "Why Silicon Valley");
}

// ---- SLIDE: India-connected catchment
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "A premium, India-connected catchment", "Strong visiting-friends-and-relatives and one-stop India demand over London");
  statCard(s, MX, 1.85, 3.55, 1.7, "209,006", "Asian Indian residents", "San Jose metro, circa 10.5% of the population", NAVY);
  statCard(s, MX+3.75, 1.85, 3.55, 1.7, "No. 1", "US county for Indian immigrants", "Santa Clara County", BLUE);
  statCard(s, MX+7.5, 1.85, 3.55, 1.7, "circa 73%", "of Bay Area H-1B workers", "Indian-born, a dense, high-yield base", TEAL);

  bullets(s, MX, 3.95, 11.9, 1.8, [
    "San Jose holds one of the densest Indian-American concentrations of any US metro. The group is high-income and degree-educated, a premium-cabin profile.",
    "This supports both visiting-friends-and-relatives travel and one-stop India connectivity over London Heathrow, feeding Delhi, Mumbai, Bengaluru and Hyderabad on BA and its partners.",
    "India demand is deliberately excluded from the base forecast to keep it conservative, so it sits as upside rather than as a headline number.",
  ], 12.5);
  sourceLine(s, "US Census Bureau ACS 2024 (B02018, B05006); Migration Policy Institute (Jun 2026); Pew Research (2025); USCIS / NFAP H-1B data.");
  footer(s, "Why Silicon Valley");
}

// ============================================================ SECTION 02
sectionDivider("02", "Two genuine\ntech centres", "London skyline / King's Cross tech quarter");

// ---- SLIDE: London end
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "The London end is a genuine peer, not a spoke", "Bay Area firms are building their largest non-US bases in London");
  statCard(s, MX, 1.85, 3.55, 1.7, "1st", "in Europe for tech", "4th globally (Dealroom 2026)", NAVY);
  statCard(s, MX+3.75, 1.85, 3.55, 1.7, "£150bn", "record US investment", "UK-US State Visit, Sept 2025", BLUE);
  statCard(s, MX+7.5, 1.85, 3.55, 1.7, "565,000 sq ft", "London office space", "taken by AI firms, early 2026", GOLD);

  bullets(s, MX, 3.95, 11.9, 2.0, [
    "Named US technology investment into the UK at the September 2025 State Visit: Microsoft £22bn, NVIDIA £11bn, Google £5bn, Salesforce and CoreWeave each over £1bn.",
    "OpenAI has made London its largest research hub outside the United States; Anthropic has taken its first permanent London office. This is senior, two-way corporate traffic of exactly the kind a daily premium service targets.",
    "London raised circa £13.2bn of tech venture funding in 2025 and is home to 138 unicorns, the largest tech ecosystem in Europe.",
  ], 12.5);
  sourceLine(s, "Dealroom Global Tech Ecosystem Index 2026; gov.uk State Visit release (17 Sept 2025); CNBC (Jun 2026); techUK.");
  footer(s, "Two tech centres");
}

// ---- SLIDE: life sciences + Heathrow corridor
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Life sciences, and a tech corridor on Heathrow's doorstep", "The demand sits physically on the Heathrow side of London");
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX, y: 1.9, w: 5.7, h: 4.0, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText("The Golden Triangle", { x: MX+0.25, y: 2.05, w: 5.2, h: 0.4, fontSize: 15, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  bullets(s, MX+0.25, 2.5, 5.2, 3.2, [
    "London - Oxford - Cambridge is the UK's largest life-sciences cluster, with circa 57% of national biopharma employment and a ranking of third in the world among life-science hubs.",
    "The Francis Crick Institute is the largest single biomedical laboratory under one roof in Europe.",
    "US capital is flowing in: Prologis committed circa £3.9bn including a major Cambridge Biomedical Campus expansion at the 2025 State Visit.",
  ], 11.5);

  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX+5.95, y: 1.9, w: 5.65, h: 4.0, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText("The Thames Valley", { x: MX+6.2, y: 2.05, w: 5.2, h: 0.4, fontSize: 15, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  bullets(s, MX+6.2, 2.5, 5.15, 3.2, [
    "The M4 / Western Corridor west of Heathrow hosts a dense technology base: Microsoft, Oracle, Cisco, NVIDIA, SAP and Dell all have UK headquarters or major operations there.",
    "Slough holds the largest data-centre concentration in Europe.",
    "Many of these firms located here for Heathrow access. Silicon Valley catchment demand therefore sits on the airport's doorstep, not only in central London.",
  ], 11.5);
  sourceLine(s, "DTRE / Lightcast / Savills (Golden Triangle, 2025); Francis Crick Institute; gov.uk (Prologis); RWA Consultants / Growth Business (Thames Valley).");
  footer(s, "Two tech centres");
}

// ---- SLIDE: trade and travel
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Trade and travel underpin the corridor", "The densest services and digital trade relationship in the world");
  statCard(s, MX, 1.85, 2.85, 1.7, "$340bn", "US-UK trade", "Two-way goods and services, 2024", NAVY);
  statCard(s, MX+3.05, 1.85, 2.85, 1.7, "£137bn", "UK services exports to US", "Professional, financial and tech, 2024", BLUE);
  statCard(s, MX+6.1, 1.85, 2.85, 1.7, "20.59m", "US-UK air passengers", "The largest US-Europe market, 2024", TEAL);
  statCard(s, MX+9.15, 1.85, 2.45, 1.7, "$1.7tn+", "two-way FDI", "Each other's largest partner", GOLD);

  bullets(s, MX, 3.95, 11.9, 1.9, [
    "The relationship is heavily services-weighted, the strongest evidence that trade drives face-to-face business travel. California's largest export line to the UK is computers and electronics, that is Silicon Valley output.",
    "The UK is the largest US-Europe country market and London Heathrow is the top US foreign gateway. Bay Area demand for London is currently funnelled almost entirely through San Francisco.",
    "Travel is deep both ways: 5.6m US visitors to the UK and 4.04m UK visitors to the US in 2024, with California the second-largest US origin region for UK-bound trips.",
  ], 12);
  sourceLine(s, "USTR; ONS UK trade with the US 2024; BEA / ONS FDI 2024; US DOT international passenger statistics 2024; VisitBritain; US NTTO.");
  footer(s, "Two tech centres");
}

// ============================================================ SECTION 03
sectionDivider("03", "San Jose airport", "SJC terminal at dusk / airfield");

// ---- SLIDE: world-class airport
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "A widebody airport at the centre of the Valley", "Closer to the cluster, and more reliable than SFO");
  statCard(s, MX, 1.85, 3.55, 1.7, "11.85m", "passengers in 2024", "Silicon Valley's home airport", NAVY);
  statCard(s, MX+3.75, 1.85, 3.55, 1.7, "36 gates", "across two terminals", "International arrivals facility, Global Entry", BLUE);
  statCard(s, MX+7.5, 1.85, 3.55, 1.7, "787-ready", "widebody capability", "ZIPAIR 787 to Tokyo operates today", TEAL);

  bullets(s, MX, 3.95, 7.4, 2.1, [
    "SJC has handled 787, A340 and larger widebodies, and BA previously planned to upsize the route to a 747-400. A daily 787 is well within the airport's capability.",
    "A genuine reliability advantage over SFO: SFO's two main landing runways are too close for side-by-side landings in low visibility and it loses half its arrival rate in fog. The same weather causes no delay at SJC.",
    "A BA service would be the only Europe nonstop at the airport.",
  ], 12);
  photoSlot(s, MX+7.7, 3.95, 3.9, 2.1, "SJC terminal interior / 787 at gate");
  sourceLine(s, "SJC Monthly Activity Report (CY2024, Jan 2025); Cranky Flier (May 2026); KQED / Cranky Flier (SFO runway geometry). 2025 figure to be confirmed from the CY2025 report.");
  footer(s, "San Jose airport");
}

// ---- SLIDE: airport support
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Airport support behind a returning service", "A de-risked launch, backed by the airport");
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX, y: 1.95, w: 7.4, h: 3.7, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText("What the airport brings", { x: MX+0.25, y: 2.1, w: 6.9, h: 0.4, fontSize: 15, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  bullets(s, MX+0.25, 2.6, 6.9, 2.9, [
    "San Jose runs an Air Service Development programme designed to encourage incremental airline route decisions, with a named air-service team.",
    "Concrete precedent of commitment: when BA exited in 2023, San Jose offered a $303,700 credit toward a future contract if the airline resumed within two years.",
    "The airport is actively talking to partners about expanding international service, and a London link is its clearest gap.",
    "Marketing support and incentive terms to be confirmed directly with the airport for the live tariff.",
  ], 12);
  statCard(s, MX+7.7, 1.95, 3.9, 1.75, "$303,700", "resumption credit offered", "Evidence of the airport's commitment", GOLD);
  photoSlot(s, MX+7.7, 3.9, 3.9, 1.75, "Airport / air service team");
  sourceLine(s, "SJC Air Service Development (flysanjose.com); Simple Flying (1 Mar 2025).");
  footer(s, "San Jose airport");
}

// ============================================================ SECTION 04
sectionDivider("04", "The forecast", "Catchment map / route visual");

// ---- SLIDE: catchment definition
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Defining the San Jose catchment", "Where San Jose is the natural airport, and where it competes with SFO");
  const cards = [
    ["Primary", "San Jose is the most convenient airport on surface access. The core of the demand.", NAVY],
    ["Secondary", "Extends south and east. Passengers would drive past SJC to reach San Francisco today, and would switch given a nonstop.", BLUE],
    ["Contested", "To the north-west, with roughly equal drive time to SJC and SFO. Shared with San Francisco.", TEAL],
  ];
  cards.forEach(([t, d, c], i) => {
    const x = MX + i*3.95;
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y: 1.95, w: 3.7, h: 2.3, fill: { color: WHITE }, line: { color: c, width: 1.5 }, rectRadius: 0.06, shadow: shadow() });
    s.addText(t, { x: x+0.22, y: 2.15, w: 3.3, h: 0.5, fontSize: 18, fontFace: HEAD, color: c, bold: true, margin: 0 });
    s.addText(d, { x: x+0.22, y: 2.75, w: 3.3, h: 1.4, fontSize: 12, fontFace: BODY, color: SLATE, margin: 0, valign: "top" });
  });
  photoSlot(s, MX, 4.5, 11.9, 1.55, "Catchment map: primary / secondary / contested drive-time bands");
  sourceLine(s, "Avia QSI catchment model (drive-time and surface-access analysis).");
  footer(s, "The forecast");
}

// ---- SLIDE: key traffic flows (bar chart)
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Key traffic flows from the catchment, beyond London", "Annual two-way demand from the San Jose service area to points over Heathrow");
  const labels = ["Paris", "Frankfurt", "Amsterdam", "Munich", "Tel Aviv", "Zurich", "Copenhagen", "Rome", "Stockholm", "Madrid"];
  const vals = [140521, 100810, 60675, 43810, 45892, 36924, 32449, 27549, 25155, 19730];
  s.addChart(pres.charts.BAR, [{ name: "Annual demand", labels, values: vals }], {
    x: MX, y: 1.85, w: 11.9, h: 4.0, barDir: "col", chartColors: [BLUE],
    showValue: true, dataLabelPosition: "outEnd", dataLabelColor: SLATE, dataLabelFontSize: 9, dataLabelFontFace: BODY,
    catAxisLabelColor: MUTED, valAxisLabelColor: MUTED, catAxisLabelFontSize: 10, valAxisLabelFontSize: 9,
    valGridLine: { color: PANEL, size: 0.5 }, catGridLine: { style: "none" }, showLegend: false,
    valAxisHidden: false, chartArea: { fill: { color: WHITE } },
  });
  sourceLine(s, "Avia QSI connecting-demand model (Sabre O&D). Validated reference case, to be refreshed on the live 2024-2025 base.");
  footer(s, "The forecast");
}

// ---- SLIDE: route forecast daily service (segment table)
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Route forecast: daily service", "Point-to-point demand by segment, with BA capture");
  const hdr = ["Segment", "Base demand", "After stimulation", "BA capture", "Forecast"].map(t =>
    ({ text: t, options: { bold: true, color: WHITE, fill: { color: NAVY }, align: t === "Segment" ? "left" : "right", fontSize: 11 } }));
  const data = [
    ["UK business", "71,400", "89,600", "40.0%", "35,800"],
    ["UK leisure / VFR", "58,400", "63,700", "circa 19%", "12,000"],
    ["US business", "65,900", "82,700", "22.0%", "18,200"],
    ["US leisure / VFR", "49,700", "53,400", "30.0%", "16,000"],
  ];
  const rows = [hdr];
  data.forEach((r, i) => rows.push(r.map((c, j) =>
    ({ text: c, options: { fill: { color: i % 2 ? LIGHT : WHITE }, color: SLATE, align: j === 0 ? "left" : "right", fontSize: 11.5 } }))));
  rows.push(["Point-to-point total", "249,800", "293,900", "28.1%", "82,700"].map((c, j) =>
    ({ text: c, options: { bold: true, fill: { color: PANEL }, color: NAVY, align: j === 0 ? "left" : "right", fontSize: 11.5 } })));
  rows.push(["Connecting at London", "991,300", "", "4.5%", "45,011"].map((c, j) =>
    ({ text: c, options: { fill: { color: WHITE }, color: SLATE, align: j === 0 ? "left" : "right", fontSize: 11.5 } })));
  rows.push(["Connecting at San Jose", "1,206,800", "", "0.2%", "2,628"].map((c, j) =>
    ({ text: c, options: { fill: { color: LIGHT }, color: SLATE, align: j === 0 ? "left" : "right", fontSize: 11.5 } })));
  rows.push(["Total, Year 1", "", "", "", "130,346"].map((c, j) =>
    ({ text: c, options: { bold: true, fill: { color: NAVY }, color: WHITE, align: j === 0 ? "left" : "right", fontSize: 12 } })));
  s.addTable(rows, { x: MX, y: 1.85, w: 11.9, colW: [3.5, 2.1, 2.1, 1.8, 2.4], fontFace: BODY,
    border: { type: "solid", pt: 0.5, color: PANEL }, valign: "middle", rowH: 0.42 });
  s.addText("Year 1 load factor 83.7% on 155,792 annual seats. India connecting demand excluded to stay conservative.",
    { x: MX, y: 5.75, w: 11.9, h: 0.35, fontSize: 11, fontFace: BODY, color: NAVY2, italic: true, margin: 0 });
  sourceLine(s, "Avia QSI forecast model (validated reference case), to be refreshed on the live 2024-2025 base.");
  footer(s, "The forecast");
}

// ---- SLIDE: connecting at London table
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Passengers connecting at London", "Top markets beyond Heathrow, with BA forecast share");
  const cities = [
    ["Paris", "140,521", "3.0%", "4,216"], ["Dublin", "28,174", "9.0%", "2,536"],
    ["Munich", "43,810", "5.4%", "2,366"], ["Cape Town", "5,893", "37.5%", "2,212"],
    ["Frankfurt", "100,810", "2.0%", "2,016"], ["Dusseldorf", "13,088", "13.7%", "1,793"],
    ["Amsterdam", "60,675", "2.9%", "1,767"], ["Stockholm", "25,155", "6.2%", "1,555"],
    ["Geneva", "12,128", "12.6%", "1,531"], ["Helsinki", "6,606", "19.6%", "1,294"],
    ["Milan", "19,567", "6.5%", "1,278"], ["Berlin", "18,020", "7.0%", "1,269"],
  ];
  const hdr = ["City", "Annual demand", "BA share", "BA forecast"].map(t =>
    ({ text: t, options: { bold: true, color: WHITE, fill: { color: NAVY }, align: t === "City" ? "left" : "right", fontSize: 11 } }));
  const left = [hdr], right = [hdr.map(h => ({ ...h, options: { ...h.options } }))];
  cities.slice(0, 6).forEach((r, i) => left.push(r.map((c, j) => ({ text: c, options: { fill: { color: i%2?LIGHT:WHITE }, color: SLATE, align: j===0?"left":"right", fontSize: 11 } }))));
  cities.slice(6).forEach((r, i) => right.push(r.map((c, j) => ({ text: c, options: { fill: { color: i%2?LIGHT:WHITE }, color: SLATE, align: j===0?"left":"right", fontSize: 11 } }))));
  s.addTable(left, { x: MX, y: 1.9, w: 5.8, colW: [1.9, 1.6, 1.0, 1.3], fontFace: BODY, border: { type: "solid", pt: 0.5, color: PANEL }, valign: "middle", rowH: 0.4 });
  s.addTable(right, { x: MX+6.1, y: 1.9, w: 5.8, colW: [1.9, 1.6, 1.0, 1.3], fontFace: BODY, border: { type: "solid", pt: 0.5, color: PANEL }, valign: "middle", rowH: 0.4 });
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX, y: 4.95, w: 11.9, h: 0.85, fill: { color: PANEL }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText([
    { text: "Total connecting market over London: 991,300 passengers a year.  ", options: { bold: true, color: NAVY } },
    { text: "BA forecast share 4.5%, circa 45,000 passengers, the equivalent of 62 a day each way.", options: { color: SLATE } },
  ], { x: MX+0.2, y: 4.95, w: 11.5, h: 0.85, fontSize: 12, fontFace: BODY, valign: "middle", margin: 0 });
  sourceLine(s, "Avia QSI connecting-demand model. Validated reference case, to be refreshed on the live 2024-2025 base.");
  footer(s, "The forecast");
}

// ---- SLIDE: connecting at San Jose
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Passengers connecting at San Jose", "Onward demand beyond SJC across the western US and Mexico");
  const cities = [
    ["Kahului (Maui)", "6,237", "16.0%", "1,000"], ["Kona", "4,815", "10.1%", "485"],
    ["Seattle", "162,580", "0.2%", "383"], ["Los Angeles", "794,266", "0.0%", "346"],
    ["Reno", "6,325", "1.5%", "98"], ["Salt Lake City", "35,222", "0.3%", "98"],
    ["Phoenix", "108,939", "0.1%", "91"], ["Portland", "39,449", "0.2%", "86"],
    ["Guadalajara", "8,999", "0.4%", "37"],
  ];
  const hdr = ["City", "Annual demand", "BA share", "BA forecast"].map(t =>
    ({ text: t, options: { bold: true, color: WHITE, fill: { color: NAVY }, align: t === "City" ? "left" : "right", fontSize: 11 } }));
  const rows = [hdr];
  cities.forEach((r, i) => rows.push(r.map((c, j) => ({ text: c, options: { fill: { color: i%2?LIGHT:WHITE }, color: SLATE, align: j===0?"left":"right", fontSize: 11 } }))));
  rows.push(["Total over San Jose", "1,206,800", "0.2%", "2,628"].map((c, j) =>
    ({ text: c, options: { bold: true, fill: { color: PANEL }, color: NAVY, align: j===0?"left":"right", fontSize: 11.5 } })));
  s.addTable(rows, { x: MX, y: 1.9, w: 7.0, colW: [2.5, 1.7, 1.2, 1.6], fontFace: BODY, border: { type: "solid", pt: 0.5, color: PANEL }, valign: "middle", rowH: 0.4 });
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX+7.3, y: 1.9, w: 4.3, h: 3.8, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText("Behind-San-Jose demand is thin", { x: MX+7.5, y: 2.05, w: 3.9, h: 0.5, fontSize: 14, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  bullets(s, MX+7.5, 2.6, 3.9, 3.0, [
    "San Jose is largely an origin and destination market, not a connecting hub, so onward connections add a modest layer.",
    "The exception is Hawaii leisure traffic, where BA can take a meaningful share.",
    "This keeps the forecast anchored on the strong point-to-point and over-London demand.",
  ], 11.5);
  sourceLine(s, "Avia QSI connecting-demand model. Validated reference case, to be refreshed on the live 2024-2025 base.");
  footer(s, "The forecast");
}

// ---- SLIDE: revenue forecast
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Revenue forecast", "Demand maturing into a high load factor over three years");
  s.addChart(pres.charts.BAR, [
    { name: "Point-to-point", labels: ["Year 1", "Year 2", "Year 3"], values: [84.6, 87.1, 89.6] },
    { name: "Connecting at London", labels: ["Year 1", "Year 2", "Year 3"], values: [26.6, 27.4, 28.2] },
    { name: "Connecting at SJC", labels: ["Year 1", "Year 2", "Year 3"], values: [2.1, 2.2, 2.2] },
    { name: "Cargo and ancillary", labels: ["Year 1", "Year 2", "Year 3"], values: [8.3, 8.7, 9.1] },
  ], {
    x: MX, y: 1.85, w: 7.2, h: 4.0, barDir: "col", barGrouping: "stacked",
    chartColors: [NAVY, BLUE, TEAL, GOLD], showLegend: true, legendPos: "b", legendColor: MUTED, legendFontSize: 9,
    catAxisLabelColor: MUTED, valAxisLabelColor: MUTED, valGridLine: { color: PANEL, size: 0.5 }, catGridLine: { style: "none" },
    valAxisTitle: "Revenue ($m)", showValAxisTitle: true, valAxisTitleColor: MUTED, valAxisTitleFontSize: 9, chartArea: { fill: { color: WHITE } },
  });
  statCard(s, MX+7.5, 1.85, 4.1, 1.25, "$121.7m", "Year 1 total revenue", "", NAVY);
  statCard(s, MX+7.5, 3.25, 4.1, 1.25, "83.7% to 88.6%", "load factor, Years 1 to 3", "", BLUE);
  statCard(s, MX+7.5, 4.65, 4.1, 1.2, "$129.2m", "Year 3 total revenue", "", GOLD);
  sourceLine(s, "Avia QSI revenue model (validated reference case). Years relabelled from the 2016-2018 reference; to be refreshed on the live base.");
  footer(s, "The forecast");
}

// ---- SLIDE: stimulation not cannibalisation
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Stimulation, not cannibalisation of San Francisco", "A distinct South Bay catchment, plus genuine new demand");
  bullets(s, MX, 1.95, 7.2, 3.7, [
    "San Jose anchors the southern Bay Area and is on average circa 40km closer to Silicon Valley headquarters than San Francisco. A BA service taps a distinct catchment rather than poaching SFO.",
    "Peer-reviewed work on first-time-served markets shows a new nonstop both diverts some connecting demand and stimulates genuinely new point-to-point traffic.",
    "The forecast is deliberately conservative: India connecting demand and US point-of-sale upsides are excluded from the base, and the contested catchment is captured at low rates.",
    "The result is net-new traffic for the airline, not a transfer from its existing London - San Francisco service.",
  ], 12);
  statCard(s, MX+7.5, 1.95, 4.1, 1.75, "circa 40km", "closer to the HQs", "SJC versus SFO", NAVY);
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX+7.5, y: 3.9, w: 4.1, h: 1.75, fill: { color: LIGHT }, line: { color: GOLD, width: 1 }, rectRadius: 0.05 });
  s.addText("Conservative by design", { x: MX+7.7, y: 4.0, w: 3.7, h: 0.4, fontSize: 13, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  s.addText("India demand, US point of sale and SFO interaction all sit as upside to the base case.",
    { x: MX+7.7, y: 4.45, w: 3.7, h: 1.1, fontSize: 11.5, fontFace: BODY, color: SLATE, margin: 0, valign: "top" });
  sourceLine(s, "Journal of Air Transport Management vol. 98 (2022); Avia Solutions catchment analysis.");
  footer(s, "The forecast");
}

// ---- SLIDE: ANA precedent
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Precedent: ANA linked Silicon Valley to Tokyo", "A premium, catchment-anchored long-haul route from San Jose");
  bullets(s, MX, 1.95, 7.2, 3.5, [
    "ANA launched San Jose to Tokyo in January 2013, the first ever nonstop between Silicon Valley and Japan, on a Boeing 787.",
    "It was configured for high-value corporate demand, with a heavy business-class cabin aimed at the Valley's Japanese technology operations.",
    "The route created a new, catchment-anchored market built on San Jose's proximity to the Valley's headquarters, the same logic that supports a London service.",
    "A BA London service would re-establish the airport's transatlantic link on exactly that premium, corporate basis.",
  ], 12);
  photoSlot(s, MX+7.5, 1.95, 4.1, 3.5, "ANA 787 at San Jose");
  sourceLine(s, "ANA; Simple Flying (2024). Market-growth versus SFO to be evidenced from US DOT T-100 Bay Area to Japan O&D.");
  footer(s, "The forecast");
}

// ============================================================ SECTION 05 content
// ---- SLIDE: methodology
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Methodology: the Avia QSI approach", "Schedule quality drives an airline's share of demand");
  const steps = [
    ["Catchment", "Drive-time and surface-access analysis sets the share of the broad market that San Jose can serve, split into primary, secondary and contested."],
    ["Point-to-point", "Sabre O&D booking data sizes the London - San Jose market, grown to the service year and stimulated for the new nonstop."],
    ["Connecting", "A Quality of Service Index scores every competing itinerary over the hub, and allocates demand to BA by relative service quality."],
    ["Revenue and economics", "Forecast passengers by cabin, priced at market fares, give revenue, with cargo and ancillary added."],
  ];
  steps.forEach(([t, d], i) => {
    const x = MX + (i%2)*5.95, y = 1.95 + Math.floor(i/2)*1.95;
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w: 5.7, h: 1.75, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05, shadow: shadow() });
    s.addText(String(i+1), { x: x+0.2, y: y+0.18, w: 0.6, h: 0.6, fontSize: 24, fontFace: HEAD, color: GOLD, bold: true, margin: 0 });
    s.addText(t, { x: x+0.85, y: y+0.2, w: 4.6, h: 0.4, fontSize: 14, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
    s.addText(d, { x: x+0.85, y: y+0.62, w: 4.7, h: 1.0, fontSize: 11, fontFace: BODY, color: SLATE, margin: 0, valign: "top" });
  });
  s.addText("Data sources: Sabre O&D demand and OAG published schedules. The method is calibrated against Avia's library of route forecasts.",
    { x: MX, y: 5.95, w: 11.9, h: 0.35, fontSize: 11, fontFace: BODY, color: NAVY2, italic: true, margin: 0 });
  footer(s, "Methodology");
}

// ---- SLIDE: why now
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "The case for now", "BA flew this route before; the market that failed it has changed");
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX, y: 1.95, w: 5.7, h: 3.8, fill: { color: LIGHT }, line: { color: PANEL, width: 1 }, rectRadius: 0.05 });
  s.addText("The honest history", { x: MX+0.25, y: 2.1, w: 5.2, h: 0.4, fontSize: 14, fontFace: HEAD, color: NAVY, bold: true, margin: 0 });
  bullets(s, MX+0.25, 2.55, 5.2, 3.0, [
    "BA served London - San Jose from 2016 to 2020, and again from 2022 to 2023.",
    "It withdrew in October 2023 on route economics and 787 fleet availability, not the pandemic.",
    "A credible relaunch case must say what is different now, rather than ignore the exit.",
  ], 11.5);

  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: MX+5.95, y: 1.95, w: 5.65, h: 3.8, fill: { color: NAVY }, rectRadius: 0.05 });
  s.addText("What has changed", { x: MX+6.2, y: 2.1, w: 5.2, h: 0.4, fontSize: 14, fontFace: HEAD, color: GOLD, bold: true, margin: 0 });
  s.addText([
    { text: "The AI economy. ", options: { bold: true, color: WHITE } },
    { text: "The Bay Area took 60% of global AI funding in 2025; this demand did not exist at scale in 2023.", options: { color: "D9E1EA", breakLine: true } },
  ], { x: MX+6.2, y: 2.6, w: 5.2, h: 0.85, fontSize: 11.5, fontFace: BODY, margin: 0, valign: "top" });
  s.addText([
    { text: "Two-way investment. ", options: { bold: true, color: WHITE } },
    { text: "A record £150bn of US tech investment into the UK, with Bay Area firms building their largest London bases.", options: { color: "D9E1EA", breakLine: true } },
  ], { x: MX+6.2, y: 3.5, w: 5.2, h: 0.85, fontSize: 11.5, fontFace: BODY, margin: 0, valign: "top" });
  s.addText([
    { text: "Airport support and a conservative forecast. ", options: { bold: true, color: WHITE } },
    { text: "Active airport backing, with India and point-of-sale upside excluded from the base.", options: { color: "D9E1EA" } },
  ], { x: MX+6.2, y: 4.4, w: 5.2, h: 1.1, fontSize: 11.5, fontFace: BODY, margin: 0, valign: "top" });
  sourceLine(s, "Simple Flying (route history); Crunchbase / HumanX (AI funding); gov.uk State Visit (Sept 2025).");
  footer(s, "The case for now");
}

// ---- SLIDE: proposed next step
{
  const s = pres.addSlide();
  s.background = { color: WHITE };
  title(s, "Proposed next step", "An invitation to see Silicon Valley first hand");
  bullets(s, MX, 1.95, 7.2, 3.3, [
    "A familiarisation visit to San Jose and Silicon Valley, hosted by the airport and its corporate partners.",
    "Meetings with the major technology employers in the catchment to confirm corporate travel commitments.",
    "A working session on schedule, aircraft and incentive terms with the airport's air-service team.",
  ], 12.5);
  photoSlot(s, MX+7.5, 1.95, 4.1, 3.3, "Levi's Stadium / Silicon Valley landmarks");
  s.addText("Co-branded with the airport and its partners.", { x: MX, y: 5.4, w: 7, h: 0.4, fontSize: 11, fontFace: BODY, color: MUTED, italic: true, margin: 0 });
  footer(s, "Next step");
}

// ---- SLIDE: close
{
  const s = pres.addSlide();
  s.background = { color: NAVY };
  s.addText("Re-establishing the link between\nLondon and Silicon Valley", { x: MX, y: 2.1, w: 11.5, h: 1.8,
    fontSize: 34, fontFace: HEAD, color: WHITE, bold: true, margin: 0, lineSpacingMultiple: 1.05 });
  s.addText("The wealthiest, most innovative and most AI-intensive metro in the world has no direct daily service to London. The market is premium, structurally connected to the City, and underserved.",
    { x: MX, y: 4.0, w: 10.5, h: 1.2, fontSize: 15, fontFace: BODY, color: "C9D4E0", margin: 0, valign: "top" });
  s.addText([
    { text: "Avia Solutions", options: { bold: true, color: GOLD, fontSize: 15, breakLine: true } },
    { text: "Route development and air service consultancy", options: { color: "AEBCCB", fontSize: 12, breakLine: true } },
    { text: "john.carter@aviasolutions.com", options: { color: "AEBCCB", fontSize: 12 } },
  ], { x: MX, y: 5.5, w: 8, h: 1.1, fontFace: BODY, margin: 0, valign: "top" });
  pageNo++;
  s.addText(String(pageNo), { x: W - 1.0, y: H - 0.42, w: 0.5, h: 0.3, fontSize: 9, fontFace: BODY, color: "8FA0B3", align: "right", margin: 0 });
}

pres.writeFile({ fileName: "BA_LHR-SJC_Route_Business_Case.pptx" }).then(f => console.log("Wrote", f));
